// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TrackerMessages.proto

package ru.itmo.java.message.tracker;

/**
 * Protobuf type {@code ru.itmo.java.message.tracker.BaseResponse}
 */
public final class BaseResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ru.itmo.java.message.tracker.BaseResponse)
    BaseResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BaseResponse.newBuilder() to construct.
  private BaseResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BaseResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BaseResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BaseResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            ru.itmo.java.message.tracker.ListResponse.Builder subBuilder = null;
            if (responseCase_ == 1) {
              subBuilder = ((ru.itmo.java.message.tracker.ListResponse) response_).toBuilder();
            }
            response_ =
                input.readMessage(ru.itmo.java.message.tracker.ListResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ru.itmo.java.message.tracker.ListResponse) response_);
              response_ = subBuilder.buildPartial();
            }
            responseCase_ = 1;
            break;
          }
          case 18: {
            ru.itmo.java.message.tracker.UploadResponse.Builder subBuilder = null;
            if (responseCase_ == 2) {
              subBuilder = ((ru.itmo.java.message.tracker.UploadResponse) response_).toBuilder();
            }
            response_ =
                input.readMessage(ru.itmo.java.message.tracker.UploadResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ru.itmo.java.message.tracker.UploadResponse) response_);
              response_ = subBuilder.buildPartial();
            }
            responseCase_ = 2;
            break;
          }
          case 26: {
            ru.itmo.java.message.tracker.SourcesResponse.Builder subBuilder = null;
            if (responseCase_ == 3) {
              subBuilder = ((ru.itmo.java.message.tracker.SourcesResponse) response_).toBuilder();
            }
            response_ =
                input.readMessage(ru.itmo.java.message.tracker.SourcesResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ru.itmo.java.message.tracker.SourcesResponse) response_);
              response_ = subBuilder.buildPartial();
            }
            responseCase_ = 3;
            break;
          }
          case 34: {
            ru.itmo.java.message.tracker.UpdateResponse.Builder subBuilder = null;
            if (responseCase_ == 4) {
              subBuilder = ((ru.itmo.java.message.tracker.UpdateResponse) response_).toBuilder();
            }
            response_ =
                input.readMessage(ru.itmo.java.message.tracker.UpdateResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ru.itmo.java.message.tracker.UpdateResponse) response_);
              response_ = subBuilder.buildPartial();
            }
            responseCase_ = 4;
            break;
          }
          case 42: {
            ru.itmo.java.message.tracker.StatResponse.Builder subBuilder = null;
            if (responseCase_ == 5) {
              subBuilder = ((ru.itmo.java.message.tracker.StatResponse) response_).toBuilder();
            }
            response_ =
                input.readMessage(ru.itmo.java.message.tracker.StatResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ru.itmo.java.message.tracker.StatResponse) response_);
              response_ = subBuilder.buildPartial();
            }
            responseCase_ = 5;
            break;
          }
          case 50: {
            ru.itmo.java.message.tracker.GetResponse.Builder subBuilder = null;
            if (responseCase_ == 6) {
              subBuilder = ((ru.itmo.java.message.tracker.GetResponse) response_).toBuilder();
            }
            response_ =
                input.readMessage(ru.itmo.java.message.tracker.GetResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ru.itmo.java.message.tracker.GetResponse) response_);
              response_ = subBuilder.buildPartial();
            }
            responseCase_ = 6;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ru.itmo.java.message.tracker.TrackerMessages.internal_static_ru_itmo_java_message_tracker_BaseResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ru.itmo.java.message.tracker.TrackerMessages.internal_static_ru_itmo_java_message_tracker_BaseResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ru.itmo.java.message.tracker.BaseResponse.class, ru.itmo.java.message.tracker.BaseResponse.Builder.class);
  }

  private int responseCase_ = 0;
  private java.lang.Object response_;
  public enum ResponseCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    LISTRESPONSE(1),
    UPLOADRESPONSE(2),
    SOURCESRESPONSE(3),
    UPDATERESPONSE(4),
    STATRESPONSE(5),
    GETRESPONSE(6),
    RESPONSE_NOT_SET(0);
    private final int value;
    private ResponseCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ResponseCase valueOf(int value) {
      return forNumber(value);
    }

    public static ResponseCase forNumber(int value) {
      switch (value) {
        case 1: return LISTRESPONSE;
        case 2: return UPLOADRESPONSE;
        case 3: return SOURCESRESPONSE;
        case 4: return UPDATERESPONSE;
        case 5: return STATRESPONSE;
        case 6: return GETRESPONSE;
        case 0: return RESPONSE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ResponseCase
  getResponseCase() {
    return ResponseCase.forNumber(
        responseCase_);
  }

  public static final int LISTRESPONSE_FIELD_NUMBER = 1;
  /**
   * <code>.ru.itmo.java.message.tracker.ListResponse listResponse = 1;</code>
   * @return Whether the listResponse field is set.
   */
  @java.lang.Override
  public boolean hasListResponse() {
    return responseCase_ == 1;
  }
  /**
   * <code>.ru.itmo.java.message.tracker.ListResponse listResponse = 1;</code>
   * @return The listResponse.
   */
  @java.lang.Override
  public ru.itmo.java.message.tracker.ListResponse getListResponse() {
    if (responseCase_ == 1) {
       return (ru.itmo.java.message.tracker.ListResponse) response_;
    }
    return ru.itmo.java.message.tracker.ListResponse.getDefaultInstance();
  }
  /**
   * <code>.ru.itmo.java.message.tracker.ListResponse listResponse = 1;</code>
   */
  @java.lang.Override
  public ru.itmo.java.message.tracker.ListResponseOrBuilder getListResponseOrBuilder() {
    if (responseCase_ == 1) {
       return (ru.itmo.java.message.tracker.ListResponse) response_;
    }
    return ru.itmo.java.message.tracker.ListResponse.getDefaultInstance();
  }

  public static final int UPLOADRESPONSE_FIELD_NUMBER = 2;
  /**
   * <code>.ru.itmo.java.message.tracker.UploadResponse uploadResponse = 2;</code>
   * @return Whether the uploadResponse field is set.
   */
  @java.lang.Override
  public boolean hasUploadResponse() {
    return responseCase_ == 2;
  }
  /**
   * <code>.ru.itmo.java.message.tracker.UploadResponse uploadResponse = 2;</code>
   * @return The uploadResponse.
   */
  @java.lang.Override
  public ru.itmo.java.message.tracker.UploadResponse getUploadResponse() {
    if (responseCase_ == 2) {
       return (ru.itmo.java.message.tracker.UploadResponse) response_;
    }
    return ru.itmo.java.message.tracker.UploadResponse.getDefaultInstance();
  }
  /**
   * <code>.ru.itmo.java.message.tracker.UploadResponse uploadResponse = 2;</code>
   */
  @java.lang.Override
  public ru.itmo.java.message.tracker.UploadResponseOrBuilder getUploadResponseOrBuilder() {
    if (responseCase_ == 2) {
       return (ru.itmo.java.message.tracker.UploadResponse) response_;
    }
    return ru.itmo.java.message.tracker.UploadResponse.getDefaultInstance();
  }

  public static final int SOURCESRESPONSE_FIELD_NUMBER = 3;
  /**
   * <code>.ru.itmo.java.message.tracker.SourcesResponse sourcesResponse = 3;</code>
   * @return Whether the sourcesResponse field is set.
   */
  @java.lang.Override
  public boolean hasSourcesResponse() {
    return responseCase_ == 3;
  }
  /**
   * <code>.ru.itmo.java.message.tracker.SourcesResponse sourcesResponse = 3;</code>
   * @return The sourcesResponse.
   */
  @java.lang.Override
  public ru.itmo.java.message.tracker.SourcesResponse getSourcesResponse() {
    if (responseCase_ == 3) {
       return (ru.itmo.java.message.tracker.SourcesResponse) response_;
    }
    return ru.itmo.java.message.tracker.SourcesResponse.getDefaultInstance();
  }
  /**
   * <code>.ru.itmo.java.message.tracker.SourcesResponse sourcesResponse = 3;</code>
   */
  @java.lang.Override
  public ru.itmo.java.message.tracker.SourcesResponseOrBuilder getSourcesResponseOrBuilder() {
    if (responseCase_ == 3) {
       return (ru.itmo.java.message.tracker.SourcesResponse) response_;
    }
    return ru.itmo.java.message.tracker.SourcesResponse.getDefaultInstance();
  }

  public static final int UPDATERESPONSE_FIELD_NUMBER = 4;
  /**
   * <code>.ru.itmo.java.message.tracker.UpdateResponse updateResponse = 4;</code>
   * @return Whether the updateResponse field is set.
   */
  @java.lang.Override
  public boolean hasUpdateResponse() {
    return responseCase_ == 4;
  }
  /**
   * <code>.ru.itmo.java.message.tracker.UpdateResponse updateResponse = 4;</code>
   * @return The updateResponse.
   */
  @java.lang.Override
  public ru.itmo.java.message.tracker.UpdateResponse getUpdateResponse() {
    if (responseCase_ == 4) {
       return (ru.itmo.java.message.tracker.UpdateResponse) response_;
    }
    return ru.itmo.java.message.tracker.UpdateResponse.getDefaultInstance();
  }
  /**
   * <code>.ru.itmo.java.message.tracker.UpdateResponse updateResponse = 4;</code>
   */
  @java.lang.Override
  public ru.itmo.java.message.tracker.UpdateResponseOrBuilder getUpdateResponseOrBuilder() {
    if (responseCase_ == 4) {
       return (ru.itmo.java.message.tracker.UpdateResponse) response_;
    }
    return ru.itmo.java.message.tracker.UpdateResponse.getDefaultInstance();
  }

  public static final int STATRESPONSE_FIELD_NUMBER = 5;
  /**
   * <code>.ru.itmo.java.message.tracker.StatResponse statResponse = 5;</code>
   * @return Whether the statResponse field is set.
   */
  @java.lang.Override
  public boolean hasStatResponse() {
    return responseCase_ == 5;
  }
  /**
   * <code>.ru.itmo.java.message.tracker.StatResponse statResponse = 5;</code>
   * @return The statResponse.
   */
  @java.lang.Override
  public ru.itmo.java.message.tracker.StatResponse getStatResponse() {
    if (responseCase_ == 5) {
       return (ru.itmo.java.message.tracker.StatResponse) response_;
    }
    return ru.itmo.java.message.tracker.StatResponse.getDefaultInstance();
  }
  /**
   * <code>.ru.itmo.java.message.tracker.StatResponse statResponse = 5;</code>
   */
  @java.lang.Override
  public ru.itmo.java.message.tracker.StatResponseOrBuilder getStatResponseOrBuilder() {
    if (responseCase_ == 5) {
       return (ru.itmo.java.message.tracker.StatResponse) response_;
    }
    return ru.itmo.java.message.tracker.StatResponse.getDefaultInstance();
  }

  public static final int GETRESPONSE_FIELD_NUMBER = 6;
  /**
   * <code>.ru.itmo.java.message.tracker.GetResponse getResponse = 6;</code>
   * @return Whether the getResponse field is set.
   */
  @java.lang.Override
  public boolean hasGetResponse() {
    return responseCase_ == 6;
  }
  /**
   * <code>.ru.itmo.java.message.tracker.GetResponse getResponse = 6;</code>
   * @return The getResponse.
   */
  @java.lang.Override
  public ru.itmo.java.message.tracker.GetResponse getGetResponse() {
    if (responseCase_ == 6) {
       return (ru.itmo.java.message.tracker.GetResponse) response_;
    }
    return ru.itmo.java.message.tracker.GetResponse.getDefaultInstance();
  }
  /**
   * <code>.ru.itmo.java.message.tracker.GetResponse getResponse = 6;</code>
   */
  @java.lang.Override
  public ru.itmo.java.message.tracker.GetResponseOrBuilder getGetResponseOrBuilder() {
    if (responseCase_ == 6) {
       return (ru.itmo.java.message.tracker.GetResponse) response_;
    }
    return ru.itmo.java.message.tracker.GetResponse.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (responseCase_ == 1) {
      output.writeMessage(1, (ru.itmo.java.message.tracker.ListResponse) response_);
    }
    if (responseCase_ == 2) {
      output.writeMessage(2, (ru.itmo.java.message.tracker.UploadResponse) response_);
    }
    if (responseCase_ == 3) {
      output.writeMessage(3, (ru.itmo.java.message.tracker.SourcesResponse) response_);
    }
    if (responseCase_ == 4) {
      output.writeMessage(4, (ru.itmo.java.message.tracker.UpdateResponse) response_);
    }
    if (responseCase_ == 5) {
      output.writeMessage(5, (ru.itmo.java.message.tracker.StatResponse) response_);
    }
    if (responseCase_ == 6) {
      output.writeMessage(6, (ru.itmo.java.message.tracker.GetResponse) response_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (responseCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (ru.itmo.java.message.tracker.ListResponse) response_);
    }
    if (responseCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (ru.itmo.java.message.tracker.UploadResponse) response_);
    }
    if (responseCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (ru.itmo.java.message.tracker.SourcesResponse) response_);
    }
    if (responseCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (ru.itmo.java.message.tracker.UpdateResponse) response_);
    }
    if (responseCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (ru.itmo.java.message.tracker.StatResponse) response_);
    }
    if (responseCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, (ru.itmo.java.message.tracker.GetResponse) response_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ru.itmo.java.message.tracker.BaseResponse)) {
      return super.equals(obj);
    }
    ru.itmo.java.message.tracker.BaseResponse other = (ru.itmo.java.message.tracker.BaseResponse) obj;

    if (!getResponseCase().equals(other.getResponseCase())) return false;
    switch (responseCase_) {
      case 1:
        if (!getListResponse()
            .equals(other.getListResponse())) return false;
        break;
      case 2:
        if (!getUploadResponse()
            .equals(other.getUploadResponse())) return false;
        break;
      case 3:
        if (!getSourcesResponse()
            .equals(other.getSourcesResponse())) return false;
        break;
      case 4:
        if (!getUpdateResponse()
            .equals(other.getUpdateResponse())) return false;
        break;
      case 5:
        if (!getStatResponse()
            .equals(other.getStatResponse())) return false;
        break;
      case 6:
        if (!getGetResponse()
            .equals(other.getGetResponse())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (responseCase_) {
      case 1:
        hash = (37 * hash) + LISTRESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getListResponse().hashCode();
        break;
      case 2:
        hash = (37 * hash) + UPLOADRESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getUploadResponse().hashCode();
        break;
      case 3:
        hash = (37 * hash) + SOURCESRESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getSourcesResponse().hashCode();
        break;
      case 4:
        hash = (37 * hash) + UPDATERESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getUpdateResponse().hashCode();
        break;
      case 5:
        hash = (37 * hash) + STATRESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getStatResponse().hashCode();
        break;
      case 6:
        hash = (37 * hash) + GETRESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getGetResponse().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ru.itmo.java.message.tracker.BaseResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.itmo.java.message.tracker.BaseResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.itmo.java.message.tracker.BaseResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.itmo.java.message.tracker.BaseResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.itmo.java.message.tracker.BaseResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.itmo.java.message.tracker.BaseResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.itmo.java.message.tracker.BaseResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.itmo.java.message.tracker.BaseResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.itmo.java.message.tracker.BaseResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ru.itmo.java.message.tracker.BaseResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.itmo.java.message.tracker.BaseResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.itmo.java.message.tracker.BaseResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ru.itmo.java.message.tracker.BaseResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ru.itmo.java.message.tracker.BaseResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ru.itmo.java.message.tracker.BaseResponse)
      ru.itmo.java.message.tracker.BaseResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.itmo.java.message.tracker.TrackerMessages.internal_static_ru_itmo_java_message_tracker_BaseResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.itmo.java.message.tracker.TrackerMessages.internal_static_ru_itmo_java_message_tracker_BaseResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.itmo.java.message.tracker.BaseResponse.class, ru.itmo.java.message.tracker.BaseResponse.Builder.class);
    }

    // Construct using ru.itmo.java.message.tracker.BaseResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      responseCase_ = 0;
      response_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ru.itmo.java.message.tracker.TrackerMessages.internal_static_ru_itmo_java_message_tracker_BaseResponse_descriptor;
    }

    @java.lang.Override
    public ru.itmo.java.message.tracker.BaseResponse getDefaultInstanceForType() {
      return ru.itmo.java.message.tracker.BaseResponse.getDefaultInstance();
    }

    @java.lang.Override
    public ru.itmo.java.message.tracker.BaseResponse build() {
      ru.itmo.java.message.tracker.BaseResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ru.itmo.java.message.tracker.BaseResponse buildPartial() {
      ru.itmo.java.message.tracker.BaseResponse result = new ru.itmo.java.message.tracker.BaseResponse(this);
      if (responseCase_ == 1) {
        if (listResponseBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = listResponseBuilder_.build();
        }
      }
      if (responseCase_ == 2) {
        if (uploadResponseBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = uploadResponseBuilder_.build();
        }
      }
      if (responseCase_ == 3) {
        if (sourcesResponseBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = sourcesResponseBuilder_.build();
        }
      }
      if (responseCase_ == 4) {
        if (updateResponseBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = updateResponseBuilder_.build();
        }
      }
      if (responseCase_ == 5) {
        if (statResponseBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = statResponseBuilder_.build();
        }
      }
      if (responseCase_ == 6) {
        if (getResponseBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = getResponseBuilder_.build();
        }
      }
      result.responseCase_ = responseCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ru.itmo.java.message.tracker.BaseResponse) {
        return mergeFrom((ru.itmo.java.message.tracker.BaseResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ru.itmo.java.message.tracker.BaseResponse other) {
      if (other == ru.itmo.java.message.tracker.BaseResponse.getDefaultInstance()) return this;
      switch (other.getResponseCase()) {
        case LISTRESPONSE: {
          mergeListResponse(other.getListResponse());
          break;
        }
        case UPLOADRESPONSE: {
          mergeUploadResponse(other.getUploadResponse());
          break;
        }
        case SOURCESRESPONSE: {
          mergeSourcesResponse(other.getSourcesResponse());
          break;
        }
        case UPDATERESPONSE: {
          mergeUpdateResponse(other.getUpdateResponse());
          break;
        }
        case STATRESPONSE: {
          mergeStatResponse(other.getStatResponse());
          break;
        }
        case GETRESPONSE: {
          mergeGetResponse(other.getGetResponse());
          break;
        }
        case RESPONSE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ru.itmo.java.message.tracker.BaseResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ru.itmo.java.message.tracker.BaseResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int responseCase_ = 0;
    private java.lang.Object response_;
    public ResponseCase
        getResponseCase() {
      return ResponseCase.forNumber(
          responseCase_);
    }

    public Builder clearResponse() {
      responseCase_ = 0;
      response_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.tracker.ListResponse, ru.itmo.java.message.tracker.ListResponse.Builder, ru.itmo.java.message.tracker.ListResponseOrBuilder> listResponseBuilder_;
    /**
     * <code>.ru.itmo.java.message.tracker.ListResponse listResponse = 1;</code>
     * @return Whether the listResponse field is set.
     */
    @java.lang.Override
    public boolean hasListResponse() {
      return responseCase_ == 1;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.ListResponse listResponse = 1;</code>
     * @return The listResponse.
     */
    @java.lang.Override
    public ru.itmo.java.message.tracker.ListResponse getListResponse() {
      if (listResponseBuilder_ == null) {
        if (responseCase_ == 1) {
          return (ru.itmo.java.message.tracker.ListResponse) response_;
        }
        return ru.itmo.java.message.tracker.ListResponse.getDefaultInstance();
      } else {
        if (responseCase_ == 1) {
          return listResponseBuilder_.getMessage();
        }
        return ru.itmo.java.message.tracker.ListResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.tracker.ListResponse listResponse = 1;</code>
     */
    public Builder setListResponse(ru.itmo.java.message.tracker.ListResponse value) {
      if (listResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        response_ = value;
        onChanged();
      } else {
        listResponseBuilder_.setMessage(value);
      }
      responseCase_ = 1;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.ListResponse listResponse = 1;</code>
     */
    public Builder setListResponse(
        ru.itmo.java.message.tracker.ListResponse.Builder builderForValue) {
      if (listResponseBuilder_ == null) {
        response_ = builderForValue.build();
        onChanged();
      } else {
        listResponseBuilder_.setMessage(builderForValue.build());
      }
      responseCase_ = 1;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.ListResponse listResponse = 1;</code>
     */
    public Builder mergeListResponse(ru.itmo.java.message.tracker.ListResponse value) {
      if (listResponseBuilder_ == null) {
        if (responseCase_ == 1 &&
            response_ != ru.itmo.java.message.tracker.ListResponse.getDefaultInstance()) {
          response_ = ru.itmo.java.message.tracker.ListResponse.newBuilder((ru.itmo.java.message.tracker.ListResponse) response_)
              .mergeFrom(value).buildPartial();
        } else {
          response_ = value;
        }
        onChanged();
      } else {
        if (responseCase_ == 1) {
          listResponseBuilder_.mergeFrom(value);
        }
        listResponseBuilder_.setMessage(value);
      }
      responseCase_ = 1;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.ListResponse listResponse = 1;</code>
     */
    public Builder clearListResponse() {
      if (listResponseBuilder_ == null) {
        if (responseCase_ == 1) {
          responseCase_ = 0;
          response_ = null;
          onChanged();
        }
      } else {
        if (responseCase_ == 1) {
          responseCase_ = 0;
          response_ = null;
        }
        listResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.ListResponse listResponse = 1;</code>
     */
    public ru.itmo.java.message.tracker.ListResponse.Builder getListResponseBuilder() {
      return getListResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.ru.itmo.java.message.tracker.ListResponse listResponse = 1;</code>
     */
    @java.lang.Override
    public ru.itmo.java.message.tracker.ListResponseOrBuilder getListResponseOrBuilder() {
      if ((responseCase_ == 1) && (listResponseBuilder_ != null)) {
        return listResponseBuilder_.getMessageOrBuilder();
      } else {
        if (responseCase_ == 1) {
          return (ru.itmo.java.message.tracker.ListResponse) response_;
        }
        return ru.itmo.java.message.tracker.ListResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.tracker.ListResponse listResponse = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.tracker.ListResponse, ru.itmo.java.message.tracker.ListResponse.Builder, ru.itmo.java.message.tracker.ListResponseOrBuilder> 
        getListResponseFieldBuilder() {
      if (listResponseBuilder_ == null) {
        if (!(responseCase_ == 1)) {
          response_ = ru.itmo.java.message.tracker.ListResponse.getDefaultInstance();
        }
        listResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ru.itmo.java.message.tracker.ListResponse, ru.itmo.java.message.tracker.ListResponse.Builder, ru.itmo.java.message.tracker.ListResponseOrBuilder>(
                (ru.itmo.java.message.tracker.ListResponse) response_,
                getParentForChildren(),
                isClean());
        response_ = null;
      }
      responseCase_ = 1;
      onChanged();;
      return listResponseBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.tracker.UploadResponse, ru.itmo.java.message.tracker.UploadResponse.Builder, ru.itmo.java.message.tracker.UploadResponseOrBuilder> uploadResponseBuilder_;
    /**
     * <code>.ru.itmo.java.message.tracker.UploadResponse uploadResponse = 2;</code>
     * @return Whether the uploadResponse field is set.
     */
    @java.lang.Override
    public boolean hasUploadResponse() {
      return responseCase_ == 2;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UploadResponse uploadResponse = 2;</code>
     * @return The uploadResponse.
     */
    @java.lang.Override
    public ru.itmo.java.message.tracker.UploadResponse getUploadResponse() {
      if (uploadResponseBuilder_ == null) {
        if (responseCase_ == 2) {
          return (ru.itmo.java.message.tracker.UploadResponse) response_;
        }
        return ru.itmo.java.message.tracker.UploadResponse.getDefaultInstance();
      } else {
        if (responseCase_ == 2) {
          return uploadResponseBuilder_.getMessage();
        }
        return ru.itmo.java.message.tracker.UploadResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UploadResponse uploadResponse = 2;</code>
     */
    public Builder setUploadResponse(ru.itmo.java.message.tracker.UploadResponse value) {
      if (uploadResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        response_ = value;
        onChanged();
      } else {
        uploadResponseBuilder_.setMessage(value);
      }
      responseCase_ = 2;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UploadResponse uploadResponse = 2;</code>
     */
    public Builder setUploadResponse(
        ru.itmo.java.message.tracker.UploadResponse.Builder builderForValue) {
      if (uploadResponseBuilder_ == null) {
        response_ = builderForValue.build();
        onChanged();
      } else {
        uploadResponseBuilder_.setMessage(builderForValue.build());
      }
      responseCase_ = 2;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UploadResponse uploadResponse = 2;</code>
     */
    public Builder mergeUploadResponse(ru.itmo.java.message.tracker.UploadResponse value) {
      if (uploadResponseBuilder_ == null) {
        if (responseCase_ == 2 &&
            response_ != ru.itmo.java.message.tracker.UploadResponse.getDefaultInstance()) {
          response_ = ru.itmo.java.message.tracker.UploadResponse.newBuilder((ru.itmo.java.message.tracker.UploadResponse) response_)
              .mergeFrom(value).buildPartial();
        } else {
          response_ = value;
        }
        onChanged();
      } else {
        if (responseCase_ == 2) {
          uploadResponseBuilder_.mergeFrom(value);
        }
        uploadResponseBuilder_.setMessage(value);
      }
      responseCase_ = 2;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UploadResponse uploadResponse = 2;</code>
     */
    public Builder clearUploadResponse() {
      if (uploadResponseBuilder_ == null) {
        if (responseCase_ == 2) {
          responseCase_ = 0;
          response_ = null;
          onChanged();
        }
      } else {
        if (responseCase_ == 2) {
          responseCase_ = 0;
          response_ = null;
        }
        uploadResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UploadResponse uploadResponse = 2;</code>
     */
    public ru.itmo.java.message.tracker.UploadResponse.Builder getUploadResponseBuilder() {
      return getUploadResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UploadResponse uploadResponse = 2;</code>
     */
    @java.lang.Override
    public ru.itmo.java.message.tracker.UploadResponseOrBuilder getUploadResponseOrBuilder() {
      if ((responseCase_ == 2) && (uploadResponseBuilder_ != null)) {
        return uploadResponseBuilder_.getMessageOrBuilder();
      } else {
        if (responseCase_ == 2) {
          return (ru.itmo.java.message.tracker.UploadResponse) response_;
        }
        return ru.itmo.java.message.tracker.UploadResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UploadResponse uploadResponse = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.tracker.UploadResponse, ru.itmo.java.message.tracker.UploadResponse.Builder, ru.itmo.java.message.tracker.UploadResponseOrBuilder> 
        getUploadResponseFieldBuilder() {
      if (uploadResponseBuilder_ == null) {
        if (!(responseCase_ == 2)) {
          response_ = ru.itmo.java.message.tracker.UploadResponse.getDefaultInstance();
        }
        uploadResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ru.itmo.java.message.tracker.UploadResponse, ru.itmo.java.message.tracker.UploadResponse.Builder, ru.itmo.java.message.tracker.UploadResponseOrBuilder>(
                (ru.itmo.java.message.tracker.UploadResponse) response_,
                getParentForChildren(),
                isClean());
        response_ = null;
      }
      responseCase_ = 2;
      onChanged();;
      return uploadResponseBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.tracker.SourcesResponse, ru.itmo.java.message.tracker.SourcesResponse.Builder, ru.itmo.java.message.tracker.SourcesResponseOrBuilder> sourcesResponseBuilder_;
    /**
     * <code>.ru.itmo.java.message.tracker.SourcesResponse sourcesResponse = 3;</code>
     * @return Whether the sourcesResponse field is set.
     */
    @java.lang.Override
    public boolean hasSourcesResponse() {
      return responseCase_ == 3;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.SourcesResponse sourcesResponse = 3;</code>
     * @return The sourcesResponse.
     */
    @java.lang.Override
    public ru.itmo.java.message.tracker.SourcesResponse getSourcesResponse() {
      if (sourcesResponseBuilder_ == null) {
        if (responseCase_ == 3) {
          return (ru.itmo.java.message.tracker.SourcesResponse) response_;
        }
        return ru.itmo.java.message.tracker.SourcesResponse.getDefaultInstance();
      } else {
        if (responseCase_ == 3) {
          return sourcesResponseBuilder_.getMessage();
        }
        return ru.itmo.java.message.tracker.SourcesResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.tracker.SourcesResponse sourcesResponse = 3;</code>
     */
    public Builder setSourcesResponse(ru.itmo.java.message.tracker.SourcesResponse value) {
      if (sourcesResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        response_ = value;
        onChanged();
      } else {
        sourcesResponseBuilder_.setMessage(value);
      }
      responseCase_ = 3;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.SourcesResponse sourcesResponse = 3;</code>
     */
    public Builder setSourcesResponse(
        ru.itmo.java.message.tracker.SourcesResponse.Builder builderForValue) {
      if (sourcesResponseBuilder_ == null) {
        response_ = builderForValue.build();
        onChanged();
      } else {
        sourcesResponseBuilder_.setMessage(builderForValue.build());
      }
      responseCase_ = 3;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.SourcesResponse sourcesResponse = 3;</code>
     */
    public Builder mergeSourcesResponse(ru.itmo.java.message.tracker.SourcesResponse value) {
      if (sourcesResponseBuilder_ == null) {
        if (responseCase_ == 3 &&
            response_ != ru.itmo.java.message.tracker.SourcesResponse.getDefaultInstance()) {
          response_ = ru.itmo.java.message.tracker.SourcesResponse.newBuilder((ru.itmo.java.message.tracker.SourcesResponse) response_)
              .mergeFrom(value).buildPartial();
        } else {
          response_ = value;
        }
        onChanged();
      } else {
        if (responseCase_ == 3) {
          sourcesResponseBuilder_.mergeFrom(value);
        }
        sourcesResponseBuilder_.setMessage(value);
      }
      responseCase_ = 3;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.SourcesResponse sourcesResponse = 3;</code>
     */
    public Builder clearSourcesResponse() {
      if (sourcesResponseBuilder_ == null) {
        if (responseCase_ == 3) {
          responseCase_ = 0;
          response_ = null;
          onChanged();
        }
      } else {
        if (responseCase_ == 3) {
          responseCase_ = 0;
          response_ = null;
        }
        sourcesResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.SourcesResponse sourcesResponse = 3;</code>
     */
    public ru.itmo.java.message.tracker.SourcesResponse.Builder getSourcesResponseBuilder() {
      return getSourcesResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.ru.itmo.java.message.tracker.SourcesResponse sourcesResponse = 3;</code>
     */
    @java.lang.Override
    public ru.itmo.java.message.tracker.SourcesResponseOrBuilder getSourcesResponseOrBuilder() {
      if ((responseCase_ == 3) && (sourcesResponseBuilder_ != null)) {
        return sourcesResponseBuilder_.getMessageOrBuilder();
      } else {
        if (responseCase_ == 3) {
          return (ru.itmo.java.message.tracker.SourcesResponse) response_;
        }
        return ru.itmo.java.message.tracker.SourcesResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.tracker.SourcesResponse sourcesResponse = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.tracker.SourcesResponse, ru.itmo.java.message.tracker.SourcesResponse.Builder, ru.itmo.java.message.tracker.SourcesResponseOrBuilder> 
        getSourcesResponseFieldBuilder() {
      if (sourcesResponseBuilder_ == null) {
        if (!(responseCase_ == 3)) {
          response_ = ru.itmo.java.message.tracker.SourcesResponse.getDefaultInstance();
        }
        sourcesResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ru.itmo.java.message.tracker.SourcesResponse, ru.itmo.java.message.tracker.SourcesResponse.Builder, ru.itmo.java.message.tracker.SourcesResponseOrBuilder>(
                (ru.itmo.java.message.tracker.SourcesResponse) response_,
                getParentForChildren(),
                isClean());
        response_ = null;
      }
      responseCase_ = 3;
      onChanged();;
      return sourcesResponseBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.tracker.UpdateResponse, ru.itmo.java.message.tracker.UpdateResponse.Builder, ru.itmo.java.message.tracker.UpdateResponseOrBuilder> updateResponseBuilder_;
    /**
     * <code>.ru.itmo.java.message.tracker.UpdateResponse updateResponse = 4;</code>
     * @return Whether the updateResponse field is set.
     */
    @java.lang.Override
    public boolean hasUpdateResponse() {
      return responseCase_ == 4;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UpdateResponse updateResponse = 4;</code>
     * @return The updateResponse.
     */
    @java.lang.Override
    public ru.itmo.java.message.tracker.UpdateResponse getUpdateResponse() {
      if (updateResponseBuilder_ == null) {
        if (responseCase_ == 4) {
          return (ru.itmo.java.message.tracker.UpdateResponse) response_;
        }
        return ru.itmo.java.message.tracker.UpdateResponse.getDefaultInstance();
      } else {
        if (responseCase_ == 4) {
          return updateResponseBuilder_.getMessage();
        }
        return ru.itmo.java.message.tracker.UpdateResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UpdateResponse updateResponse = 4;</code>
     */
    public Builder setUpdateResponse(ru.itmo.java.message.tracker.UpdateResponse value) {
      if (updateResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        response_ = value;
        onChanged();
      } else {
        updateResponseBuilder_.setMessage(value);
      }
      responseCase_ = 4;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UpdateResponse updateResponse = 4;</code>
     */
    public Builder setUpdateResponse(
        ru.itmo.java.message.tracker.UpdateResponse.Builder builderForValue) {
      if (updateResponseBuilder_ == null) {
        response_ = builderForValue.build();
        onChanged();
      } else {
        updateResponseBuilder_.setMessage(builderForValue.build());
      }
      responseCase_ = 4;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UpdateResponse updateResponse = 4;</code>
     */
    public Builder mergeUpdateResponse(ru.itmo.java.message.tracker.UpdateResponse value) {
      if (updateResponseBuilder_ == null) {
        if (responseCase_ == 4 &&
            response_ != ru.itmo.java.message.tracker.UpdateResponse.getDefaultInstance()) {
          response_ = ru.itmo.java.message.tracker.UpdateResponse.newBuilder((ru.itmo.java.message.tracker.UpdateResponse) response_)
              .mergeFrom(value).buildPartial();
        } else {
          response_ = value;
        }
        onChanged();
      } else {
        if (responseCase_ == 4) {
          updateResponseBuilder_.mergeFrom(value);
        }
        updateResponseBuilder_.setMessage(value);
      }
      responseCase_ = 4;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UpdateResponse updateResponse = 4;</code>
     */
    public Builder clearUpdateResponse() {
      if (updateResponseBuilder_ == null) {
        if (responseCase_ == 4) {
          responseCase_ = 0;
          response_ = null;
          onChanged();
        }
      } else {
        if (responseCase_ == 4) {
          responseCase_ = 0;
          response_ = null;
        }
        updateResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UpdateResponse updateResponse = 4;</code>
     */
    public ru.itmo.java.message.tracker.UpdateResponse.Builder getUpdateResponseBuilder() {
      return getUpdateResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UpdateResponse updateResponse = 4;</code>
     */
    @java.lang.Override
    public ru.itmo.java.message.tracker.UpdateResponseOrBuilder getUpdateResponseOrBuilder() {
      if ((responseCase_ == 4) && (updateResponseBuilder_ != null)) {
        return updateResponseBuilder_.getMessageOrBuilder();
      } else {
        if (responseCase_ == 4) {
          return (ru.itmo.java.message.tracker.UpdateResponse) response_;
        }
        return ru.itmo.java.message.tracker.UpdateResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UpdateResponse updateResponse = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.tracker.UpdateResponse, ru.itmo.java.message.tracker.UpdateResponse.Builder, ru.itmo.java.message.tracker.UpdateResponseOrBuilder> 
        getUpdateResponseFieldBuilder() {
      if (updateResponseBuilder_ == null) {
        if (!(responseCase_ == 4)) {
          response_ = ru.itmo.java.message.tracker.UpdateResponse.getDefaultInstance();
        }
        updateResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ru.itmo.java.message.tracker.UpdateResponse, ru.itmo.java.message.tracker.UpdateResponse.Builder, ru.itmo.java.message.tracker.UpdateResponseOrBuilder>(
                (ru.itmo.java.message.tracker.UpdateResponse) response_,
                getParentForChildren(),
                isClean());
        response_ = null;
      }
      responseCase_ = 4;
      onChanged();;
      return updateResponseBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.tracker.StatResponse, ru.itmo.java.message.tracker.StatResponse.Builder, ru.itmo.java.message.tracker.StatResponseOrBuilder> statResponseBuilder_;
    /**
     * <code>.ru.itmo.java.message.tracker.StatResponse statResponse = 5;</code>
     * @return Whether the statResponse field is set.
     */
    @java.lang.Override
    public boolean hasStatResponse() {
      return responseCase_ == 5;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.StatResponse statResponse = 5;</code>
     * @return The statResponse.
     */
    @java.lang.Override
    public ru.itmo.java.message.tracker.StatResponse getStatResponse() {
      if (statResponseBuilder_ == null) {
        if (responseCase_ == 5) {
          return (ru.itmo.java.message.tracker.StatResponse) response_;
        }
        return ru.itmo.java.message.tracker.StatResponse.getDefaultInstance();
      } else {
        if (responseCase_ == 5) {
          return statResponseBuilder_.getMessage();
        }
        return ru.itmo.java.message.tracker.StatResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.tracker.StatResponse statResponse = 5;</code>
     */
    public Builder setStatResponse(ru.itmo.java.message.tracker.StatResponse value) {
      if (statResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        response_ = value;
        onChanged();
      } else {
        statResponseBuilder_.setMessage(value);
      }
      responseCase_ = 5;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.StatResponse statResponse = 5;</code>
     */
    public Builder setStatResponse(
        ru.itmo.java.message.tracker.StatResponse.Builder builderForValue) {
      if (statResponseBuilder_ == null) {
        response_ = builderForValue.build();
        onChanged();
      } else {
        statResponseBuilder_.setMessage(builderForValue.build());
      }
      responseCase_ = 5;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.StatResponse statResponse = 5;</code>
     */
    public Builder mergeStatResponse(ru.itmo.java.message.tracker.StatResponse value) {
      if (statResponseBuilder_ == null) {
        if (responseCase_ == 5 &&
            response_ != ru.itmo.java.message.tracker.StatResponse.getDefaultInstance()) {
          response_ = ru.itmo.java.message.tracker.StatResponse.newBuilder((ru.itmo.java.message.tracker.StatResponse) response_)
              .mergeFrom(value).buildPartial();
        } else {
          response_ = value;
        }
        onChanged();
      } else {
        if (responseCase_ == 5) {
          statResponseBuilder_.mergeFrom(value);
        }
        statResponseBuilder_.setMessage(value);
      }
      responseCase_ = 5;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.StatResponse statResponse = 5;</code>
     */
    public Builder clearStatResponse() {
      if (statResponseBuilder_ == null) {
        if (responseCase_ == 5) {
          responseCase_ = 0;
          response_ = null;
          onChanged();
        }
      } else {
        if (responseCase_ == 5) {
          responseCase_ = 0;
          response_ = null;
        }
        statResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.StatResponse statResponse = 5;</code>
     */
    public ru.itmo.java.message.tracker.StatResponse.Builder getStatResponseBuilder() {
      return getStatResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.ru.itmo.java.message.tracker.StatResponse statResponse = 5;</code>
     */
    @java.lang.Override
    public ru.itmo.java.message.tracker.StatResponseOrBuilder getStatResponseOrBuilder() {
      if ((responseCase_ == 5) && (statResponseBuilder_ != null)) {
        return statResponseBuilder_.getMessageOrBuilder();
      } else {
        if (responseCase_ == 5) {
          return (ru.itmo.java.message.tracker.StatResponse) response_;
        }
        return ru.itmo.java.message.tracker.StatResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.tracker.StatResponse statResponse = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.tracker.StatResponse, ru.itmo.java.message.tracker.StatResponse.Builder, ru.itmo.java.message.tracker.StatResponseOrBuilder> 
        getStatResponseFieldBuilder() {
      if (statResponseBuilder_ == null) {
        if (!(responseCase_ == 5)) {
          response_ = ru.itmo.java.message.tracker.StatResponse.getDefaultInstance();
        }
        statResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ru.itmo.java.message.tracker.StatResponse, ru.itmo.java.message.tracker.StatResponse.Builder, ru.itmo.java.message.tracker.StatResponseOrBuilder>(
                (ru.itmo.java.message.tracker.StatResponse) response_,
                getParentForChildren(),
                isClean());
        response_ = null;
      }
      responseCase_ = 5;
      onChanged();;
      return statResponseBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.tracker.GetResponse, ru.itmo.java.message.tracker.GetResponse.Builder, ru.itmo.java.message.tracker.GetResponseOrBuilder> getResponseBuilder_;
    /**
     * <code>.ru.itmo.java.message.tracker.GetResponse getResponse = 6;</code>
     * @return Whether the getResponse field is set.
     */
    @java.lang.Override
    public boolean hasGetResponse() {
      return responseCase_ == 6;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.GetResponse getResponse = 6;</code>
     * @return The getResponse.
     */
    @java.lang.Override
    public ru.itmo.java.message.tracker.GetResponse getGetResponse() {
      if (getResponseBuilder_ == null) {
        if (responseCase_ == 6) {
          return (ru.itmo.java.message.tracker.GetResponse) response_;
        }
        return ru.itmo.java.message.tracker.GetResponse.getDefaultInstance();
      } else {
        if (responseCase_ == 6) {
          return getResponseBuilder_.getMessage();
        }
        return ru.itmo.java.message.tracker.GetResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.tracker.GetResponse getResponse = 6;</code>
     */
    public Builder setGetResponse(ru.itmo.java.message.tracker.GetResponse value) {
      if (getResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        response_ = value;
        onChanged();
      } else {
        getResponseBuilder_.setMessage(value);
      }
      responseCase_ = 6;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.GetResponse getResponse = 6;</code>
     */
    public Builder setGetResponse(
        ru.itmo.java.message.tracker.GetResponse.Builder builderForValue) {
      if (getResponseBuilder_ == null) {
        response_ = builderForValue.build();
        onChanged();
      } else {
        getResponseBuilder_.setMessage(builderForValue.build());
      }
      responseCase_ = 6;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.GetResponse getResponse = 6;</code>
     */
    public Builder mergeGetResponse(ru.itmo.java.message.tracker.GetResponse value) {
      if (getResponseBuilder_ == null) {
        if (responseCase_ == 6 &&
            response_ != ru.itmo.java.message.tracker.GetResponse.getDefaultInstance()) {
          response_ = ru.itmo.java.message.tracker.GetResponse.newBuilder((ru.itmo.java.message.tracker.GetResponse) response_)
              .mergeFrom(value).buildPartial();
        } else {
          response_ = value;
        }
        onChanged();
      } else {
        if (responseCase_ == 6) {
          getResponseBuilder_.mergeFrom(value);
        }
        getResponseBuilder_.setMessage(value);
      }
      responseCase_ = 6;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.GetResponse getResponse = 6;</code>
     */
    public Builder clearGetResponse() {
      if (getResponseBuilder_ == null) {
        if (responseCase_ == 6) {
          responseCase_ = 0;
          response_ = null;
          onChanged();
        }
      } else {
        if (responseCase_ == 6) {
          responseCase_ = 0;
          response_ = null;
        }
        getResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.GetResponse getResponse = 6;</code>
     */
    public ru.itmo.java.message.tracker.GetResponse.Builder getGetResponseBuilder() {
      return getGetResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.ru.itmo.java.message.tracker.GetResponse getResponse = 6;</code>
     */
    @java.lang.Override
    public ru.itmo.java.message.tracker.GetResponseOrBuilder getGetResponseOrBuilder() {
      if ((responseCase_ == 6) && (getResponseBuilder_ != null)) {
        return getResponseBuilder_.getMessageOrBuilder();
      } else {
        if (responseCase_ == 6) {
          return (ru.itmo.java.message.tracker.GetResponse) response_;
        }
        return ru.itmo.java.message.tracker.GetResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.tracker.GetResponse getResponse = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.tracker.GetResponse, ru.itmo.java.message.tracker.GetResponse.Builder, ru.itmo.java.message.tracker.GetResponseOrBuilder> 
        getGetResponseFieldBuilder() {
      if (getResponseBuilder_ == null) {
        if (!(responseCase_ == 6)) {
          response_ = ru.itmo.java.message.tracker.GetResponse.getDefaultInstance();
        }
        getResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ru.itmo.java.message.tracker.GetResponse, ru.itmo.java.message.tracker.GetResponse.Builder, ru.itmo.java.message.tracker.GetResponseOrBuilder>(
                (ru.itmo.java.message.tracker.GetResponse) response_,
                getParentForChildren(),
                isClean());
        response_ = null;
      }
      responseCase_ = 6;
      onChanged();;
      return getResponseBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ru.itmo.java.message.tracker.BaseResponse)
  }

  // @@protoc_insertion_point(class_scope:ru.itmo.java.message.tracker.BaseResponse)
  private static final ru.itmo.java.message.tracker.BaseResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ru.itmo.java.message.tracker.BaseResponse();
  }

  public static ru.itmo.java.message.tracker.BaseResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BaseResponse>
      PARSER = new com.google.protobuf.AbstractParser<BaseResponse>() {
    @java.lang.Override
    public BaseResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BaseResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BaseResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BaseResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ru.itmo.java.message.tracker.BaseResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

