// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TrackerMessages.proto

package ru.itmo.java.message.tracker;

/**
 * Protobuf type {@code ru.itmo.java.message.tracker.BaseRequest}
 */
public final class BaseRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ru.itmo.java.message.tracker.BaseRequest)
    BaseRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BaseRequest.newBuilder() to construct.
  private BaseRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BaseRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BaseRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BaseRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            ru.itmo.java.message.tracker.ListRequest.Builder subBuilder = null;
            if (requestCase_ == 1) {
              subBuilder = ((ru.itmo.java.message.tracker.ListRequest) request_).toBuilder();
            }
            request_ =
                input.readMessage(ru.itmo.java.message.tracker.ListRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ru.itmo.java.message.tracker.ListRequest) request_);
              request_ = subBuilder.buildPartial();
            }
            requestCase_ = 1;
            break;
          }
          case 18: {
            ru.itmo.java.message.tracker.UploadRequest.Builder subBuilder = null;
            if (requestCase_ == 2) {
              subBuilder = ((ru.itmo.java.message.tracker.UploadRequest) request_).toBuilder();
            }
            request_ =
                input.readMessage(ru.itmo.java.message.tracker.UploadRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ru.itmo.java.message.tracker.UploadRequest) request_);
              request_ = subBuilder.buildPartial();
            }
            requestCase_ = 2;
            break;
          }
          case 26: {
            ru.itmo.java.message.tracker.SourcesRequest.Builder subBuilder = null;
            if (requestCase_ == 3) {
              subBuilder = ((ru.itmo.java.message.tracker.SourcesRequest) request_).toBuilder();
            }
            request_ =
                input.readMessage(ru.itmo.java.message.tracker.SourcesRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ru.itmo.java.message.tracker.SourcesRequest) request_);
              request_ = subBuilder.buildPartial();
            }
            requestCase_ = 3;
            break;
          }
          case 34: {
            ru.itmo.java.message.tracker.UpdateRequest.Builder subBuilder = null;
            if (requestCase_ == 4) {
              subBuilder = ((ru.itmo.java.message.tracker.UpdateRequest) request_).toBuilder();
            }
            request_ =
                input.readMessage(ru.itmo.java.message.tracker.UpdateRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ru.itmo.java.message.tracker.UpdateRequest) request_);
              request_ = subBuilder.buildPartial();
            }
            requestCase_ = 4;
            break;
          }
          case 42: {
            ru.itmo.java.message.tracker.StatRequest.Builder subBuilder = null;
            if (requestCase_ == 5) {
              subBuilder = ((ru.itmo.java.message.tracker.StatRequest) request_).toBuilder();
            }
            request_ =
                input.readMessage(ru.itmo.java.message.tracker.StatRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ru.itmo.java.message.tracker.StatRequest) request_);
              request_ = subBuilder.buildPartial();
            }
            requestCase_ = 5;
            break;
          }
          case 50: {
            ru.itmo.java.message.tracker.GetRequest.Builder subBuilder = null;
            if (requestCase_ == 6) {
              subBuilder = ((ru.itmo.java.message.tracker.GetRequest) request_).toBuilder();
            }
            request_ =
                input.readMessage(ru.itmo.java.message.tracker.GetRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ru.itmo.java.message.tracker.GetRequest) request_);
              request_ = subBuilder.buildPartial();
            }
            requestCase_ = 6;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ru.itmo.java.message.tracker.TrackerMessages.internal_static_ru_itmo_java_message_tracker_BaseRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ru.itmo.java.message.tracker.TrackerMessages.internal_static_ru_itmo_java_message_tracker_BaseRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ru.itmo.java.message.tracker.BaseRequest.class, ru.itmo.java.message.tracker.BaseRequest.Builder.class);
  }

  private int requestCase_ = 0;
  private java.lang.Object request_;
  public enum RequestCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    LISTREQUEST(1),
    UPLOADREQUEST(2),
    SOURCESREQUEST(3),
    UPDATEREQUEST(4),
    STATREQUEST(5),
    GETREQUEST(6),
    REQUEST_NOT_SET(0);
    private final int value;
    private RequestCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RequestCase valueOf(int value) {
      return forNumber(value);
    }

    public static RequestCase forNumber(int value) {
      switch (value) {
        case 1: return LISTREQUEST;
        case 2: return UPLOADREQUEST;
        case 3: return SOURCESREQUEST;
        case 4: return UPDATEREQUEST;
        case 5: return STATREQUEST;
        case 6: return GETREQUEST;
        case 0: return REQUEST_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public RequestCase
  getRequestCase() {
    return RequestCase.forNumber(
        requestCase_);
  }

  public static final int LISTREQUEST_FIELD_NUMBER = 1;
  /**
   * <code>.ru.itmo.java.message.tracker.ListRequest listRequest = 1;</code>
   * @return Whether the listRequest field is set.
   */
  @java.lang.Override
  public boolean hasListRequest() {
    return requestCase_ == 1;
  }
  /**
   * <code>.ru.itmo.java.message.tracker.ListRequest listRequest = 1;</code>
   * @return The listRequest.
   */
  @java.lang.Override
  public ru.itmo.java.message.tracker.ListRequest getListRequest() {
    if (requestCase_ == 1) {
       return (ru.itmo.java.message.tracker.ListRequest) request_;
    }
    return ru.itmo.java.message.tracker.ListRequest.getDefaultInstance();
  }
  /**
   * <code>.ru.itmo.java.message.tracker.ListRequest listRequest = 1;</code>
   */
  @java.lang.Override
  public ru.itmo.java.message.tracker.ListRequestOrBuilder getListRequestOrBuilder() {
    if (requestCase_ == 1) {
       return (ru.itmo.java.message.tracker.ListRequest) request_;
    }
    return ru.itmo.java.message.tracker.ListRequest.getDefaultInstance();
  }

  public static final int UPLOADREQUEST_FIELD_NUMBER = 2;
  /**
   * <code>.ru.itmo.java.message.tracker.UploadRequest uploadRequest = 2;</code>
   * @return Whether the uploadRequest field is set.
   */
  @java.lang.Override
  public boolean hasUploadRequest() {
    return requestCase_ == 2;
  }
  /**
   * <code>.ru.itmo.java.message.tracker.UploadRequest uploadRequest = 2;</code>
   * @return The uploadRequest.
   */
  @java.lang.Override
  public ru.itmo.java.message.tracker.UploadRequest getUploadRequest() {
    if (requestCase_ == 2) {
       return (ru.itmo.java.message.tracker.UploadRequest) request_;
    }
    return ru.itmo.java.message.tracker.UploadRequest.getDefaultInstance();
  }
  /**
   * <code>.ru.itmo.java.message.tracker.UploadRequest uploadRequest = 2;</code>
   */
  @java.lang.Override
  public ru.itmo.java.message.tracker.UploadRequestOrBuilder getUploadRequestOrBuilder() {
    if (requestCase_ == 2) {
       return (ru.itmo.java.message.tracker.UploadRequest) request_;
    }
    return ru.itmo.java.message.tracker.UploadRequest.getDefaultInstance();
  }

  public static final int SOURCESREQUEST_FIELD_NUMBER = 3;
  /**
   * <code>.ru.itmo.java.message.tracker.SourcesRequest sourcesRequest = 3;</code>
   * @return Whether the sourcesRequest field is set.
   */
  @java.lang.Override
  public boolean hasSourcesRequest() {
    return requestCase_ == 3;
  }
  /**
   * <code>.ru.itmo.java.message.tracker.SourcesRequest sourcesRequest = 3;</code>
   * @return The sourcesRequest.
   */
  @java.lang.Override
  public ru.itmo.java.message.tracker.SourcesRequest getSourcesRequest() {
    if (requestCase_ == 3) {
       return (ru.itmo.java.message.tracker.SourcesRequest) request_;
    }
    return ru.itmo.java.message.tracker.SourcesRequest.getDefaultInstance();
  }
  /**
   * <code>.ru.itmo.java.message.tracker.SourcesRequest sourcesRequest = 3;</code>
   */
  @java.lang.Override
  public ru.itmo.java.message.tracker.SourcesRequestOrBuilder getSourcesRequestOrBuilder() {
    if (requestCase_ == 3) {
       return (ru.itmo.java.message.tracker.SourcesRequest) request_;
    }
    return ru.itmo.java.message.tracker.SourcesRequest.getDefaultInstance();
  }

  public static final int UPDATEREQUEST_FIELD_NUMBER = 4;
  /**
   * <code>.ru.itmo.java.message.tracker.UpdateRequest updateRequest = 4;</code>
   * @return Whether the updateRequest field is set.
   */
  @java.lang.Override
  public boolean hasUpdateRequest() {
    return requestCase_ == 4;
  }
  /**
   * <code>.ru.itmo.java.message.tracker.UpdateRequest updateRequest = 4;</code>
   * @return The updateRequest.
   */
  @java.lang.Override
  public ru.itmo.java.message.tracker.UpdateRequest getUpdateRequest() {
    if (requestCase_ == 4) {
       return (ru.itmo.java.message.tracker.UpdateRequest) request_;
    }
    return ru.itmo.java.message.tracker.UpdateRequest.getDefaultInstance();
  }
  /**
   * <code>.ru.itmo.java.message.tracker.UpdateRequest updateRequest = 4;</code>
   */
  @java.lang.Override
  public ru.itmo.java.message.tracker.UpdateRequestOrBuilder getUpdateRequestOrBuilder() {
    if (requestCase_ == 4) {
       return (ru.itmo.java.message.tracker.UpdateRequest) request_;
    }
    return ru.itmo.java.message.tracker.UpdateRequest.getDefaultInstance();
  }

  public static final int STATREQUEST_FIELD_NUMBER = 5;
  /**
   * <code>.ru.itmo.java.message.tracker.StatRequest statRequest = 5;</code>
   * @return Whether the statRequest field is set.
   */
  @java.lang.Override
  public boolean hasStatRequest() {
    return requestCase_ == 5;
  }
  /**
   * <code>.ru.itmo.java.message.tracker.StatRequest statRequest = 5;</code>
   * @return The statRequest.
   */
  @java.lang.Override
  public ru.itmo.java.message.tracker.StatRequest getStatRequest() {
    if (requestCase_ == 5) {
       return (ru.itmo.java.message.tracker.StatRequest) request_;
    }
    return ru.itmo.java.message.tracker.StatRequest.getDefaultInstance();
  }
  /**
   * <code>.ru.itmo.java.message.tracker.StatRequest statRequest = 5;</code>
   */
  @java.lang.Override
  public ru.itmo.java.message.tracker.StatRequestOrBuilder getStatRequestOrBuilder() {
    if (requestCase_ == 5) {
       return (ru.itmo.java.message.tracker.StatRequest) request_;
    }
    return ru.itmo.java.message.tracker.StatRequest.getDefaultInstance();
  }

  public static final int GETREQUEST_FIELD_NUMBER = 6;
  /**
   * <code>.ru.itmo.java.message.tracker.GetRequest getRequest = 6;</code>
   * @return Whether the getRequest field is set.
   */
  @java.lang.Override
  public boolean hasGetRequest() {
    return requestCase_ == 6;
  }
  /**
   * <code>.ru.itmo.java.message.tracker.GetRequest getRequest = 6;</code>
   * @return The getRequest.
   */
  @java.lang.Override
  public ru.itmo.java.message.tracker.GetRequest getGetRequest() {
    if (requestCase_ == 6) {
       return (ru.itmo.java.message.tracker.GetRequest) request_;
    }
    return ru.itmo.java.message.tracker.GetRequest.getDefaultInstance();
  }
  /**
   * <code>.ru.itmo.java.message.tracker.GetRequest getRequest = 6;</code>
   */
  @java.lang.Override
  public ru.itmo.java.message.tracker.GetRequestOrBuilder getGetRequestOrBuilder() {
    if (requestCase_ == 6) {
       return (ru.itmo.java.message.tracker.GetRequest) request_;
    }
    return ru.itmo.java.message.tracker.GetRequest.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (requestCase_ == 1) {
      output.writeMessage(1, (ru.itmo.java.message.tracker.ListRequest) request_);
    }
    if (requestCase_ == 2) {
      output.writeMessage(2, (ru.itmo.java.message.tracker.UploadRequest) request_);
    }
    if (requestCase_ == 3) {
      output.writeMessage(3, (ru.itmo.java.message.tracker.SourcesRequest) request_);
    }
    if (requestCase_ == 4) {
      output.writeMessage(4, (ru.itmo.java.message.tracker.UpdateRequest) request_);
    }
    if (requestCase_ == 5) {
      output.writeMessage(5, (ru.itmo.java.message.tracker.StatRequest) request_);
    }
    if (requestCase_ == 6) {
      output.writeMessage(6, (ru.itmo.java.message.tracker.GetRequest) request_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (requestCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (ru.itmo.java.message.tracker.ListRequest) request_);
    }
    if (requestCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (ru.itmo.java.message.tracker.UploadRequest) request_);
    }
    if (requestCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (ru.itmo.java.message.tracker.SourcesRequest) request_);
    }
    if (requestCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (ru.itmo.java.message.tracker.UpdateRequest) request_);
    }
    if (requestCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (ru.itmo.java.message.tracker.StatRequest) request_);
    }
    if (requestCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, (ru.itmo.java.message.tracker.GetRequest) request_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ru.itmo.java.message.tracker.BaseRequest)) {
      return super.equals(obj);
    }
    ru.itmo.java.message.tracker.BaseRequest other = (ru.itmo.java.message.tracker.BaseRequest) obj;

    if (!getRequestCase().equals(other.getRequestCase())) return false;
    switch (requestCase_) {
      case 1:
        if (!getListRequest()
            .equals(other.getListRequest())) return false;
        break;
      case 2:
        if (!getUploadRequest()
            .equals(other.getUploadRequest())) return false;
        break;
      case 3:
        if (!getSourcesRequest()
            .equals(other.getSourcesRequest())) return false;
        break;
      case 4:
        if (!getUpdateRequest()
            .equals(other.getUpdateRequest())) return false;
        break;
      case 5:
        if (!getStatRequest()
            .equals(other.getStatRequest())) return false;
        break;
      case 6:
        if (!getGetRequest()
            .equals(other.getGetRequest())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (requestCase_) {
      case 1:
        hash = (37 * hash) + LISTREQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getListRequest().hashCode();
        break;
      case 2:
        hash = (37 * hash) + UPLOADREQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getUploadRequest().hashCode();
        break;
      case 3:
        hash = (37 * hash) + SOURCESREQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getSourcesRequest().hashCode();
        break;
      case 4:
        hash = (37 * hash) + UPDATEREQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getUpdateRequest().hashCode();
        break;
      case 5:
        hash = (37 * hash) + STATREQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getStatRequest().hashCode();
        break;
      case 6:
        hash = (37 * hash) + GETREQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getGetRequest().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ru.itmo.java.message.tracker.BaseRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.itmo.java.message.tracker.BaseRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.itmo.java.message.tracker.BaseRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.itmo.java.message.tracker.BaseRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.itmo.java.message.tracker.BaseRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.itmo.java.message.tracker.BaseRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.itmo.java.message.tracker.BaseRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.itmo.java.message.tracker.BaseRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.itmo.java.message.tracker.BaseRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ru.itmo.java.message.tracker.BaseRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.itmo.java.message.tracker.BaseRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.itmo.java.message.tracker.BaseRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ru.itmo.java.message.tracker.BaseRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ru.itmo.java.message.tracker.BaseRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ru.itmo.java.message.tracker.BaseRequest)
      ru.itmo.java.message.tracker.BaseRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.itmo.java.message.tracker.TrackerMessages.internal_static_ru_itmo_java_message_tracker_BaseRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.itmo.java.message.tracker.TrackerMessages.internal_static_ru_itmo_java_message_tracker_BaseRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.itmo.java.message.tracker.BaseRequest.class, ru.itmo.java.message.tracker.BaseRequest.Builder.class);
    }

    // Construct using ru.itmo.java.message.tracker.BaseRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      requestCase_ = 0;
      request_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ru.itmo.java.message.tracker.TrackerMessages.internal_static_ru_itmo_java_message_tracker_BaseRequest_descriptor;
    }

    @java.lang.Override
    public ru.itmo.java.message.tracker.BaseRequest getDefaultInstanceForType() {
      return ru.itmo.java.message.tracker.BaseRequest.getDefaultInstance();
    }

    @java.lang.Override
    public ru.itmo.java.message.tracker.BaseRequest build() {
      ru.itmo.java.message.tracker.BaseRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ru.itmo.java.message.tracker.BaseRequest buildPartial() {
      ru.itmo.java.message.tracker.BaseRequest result = new ru.itmo.java.message.tracker.BaseRequest(this);
      if (requestCase_ == 1) {
        if (listRequestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = listRequestBuilder_.build();
        }
      }
      if (requestCase_ == 2) {
        if (uploadRequestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = uploadRequestBuilder_.build();
        }
      }
      if (requestCase_ == 3) {
        if (sourcesRequestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = sourcesRequestBuilder_.build();
        }
      }
      if (requestCase_ == 4) {
        if (updateRequestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = updateRequestBuilder_.build();
        }
      }
      if (requestCase_ == 5) {
        if (statRequestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = statRequestBuilder_.build();
        }
      }
      if (requestCase_ == 6) {
        if (getRequestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = getRequestBuilder_.build();
        }
      }
      result.requestCase_ = requestCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ru.itmo.java.message.tracker.BaseRequest) {
        return mergeFrom((ru.itmo.java.message.tracker.BaseRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ru.itmo.java.message.tracker.BaseRequest other) {
      if (other == ru.itmo.java.message.tracker.BaseRequest.getDefaultInstance()) return this;
      switch (other.getRequestCase()) {
        case LISTREQUEST: {
          mergeListRequest(other.getListRequest());
          break;
        }
        case UPLOADREQUEST: {
          mergeUploadRequest(other.getUploadRequest());
          break;
        }
        case SOURCESREQUEST: {
          mergeSourcesRequest(other.getSourcesRequest());
          break;
        }
        case UPDATEREQUEST: {
          mergeUpdateRequest(other.getUpdateRequest());
          break;
        }
        case STATREQUEST: {
          mergeStatRequest(other.getStatRequest());
          break;
        }
        case GETREQUEST: {
          mergeGetRequest(other.getGetRequest());
          break;
        }
        case REQUEST_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ru.itmo.java.message.tracker.BaseRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ru.itmo.java.message.tracker.BaseRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int requestCase_ = 0;
    private java.lang.Object request_;
    public RequestCase
        getRequestCase() {
      return RequestCase.forNumber(
          requestCase_);
    }

    public Builder clearRequest() {
      requestCase_ = 0;
      request_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.tracker.ListRequest, ru.itmo.java.message.tracker.ListRequest.Builder, ru.itmo.java.message.tracker.ListRequestOrBuilder> listRequestBuilder_;
    /**
     * <code>.ru.itmo.java.message.tracker.ListRequest listRequest = 1;</code>
     * @return Whether the listRequest field is set.
     */
    @java.lang.Override
    public boolean hasListRequest() {
      return requestCase_ == 1;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.ListRequest listRequest = 1;</code>
     * @return The listRequest.
     */
    @java.lang.Override
    public ru.itmo.java.message.tracker.ListRequest getListRequest() {
      if (listRequestBuilder_ == null) {
        if (requestCase_ == 1) {
          return (ru.itmo.java.message.tracker.ListRequest) request_;
        }
        return ru.itmo.java.message.tracker.ListRequest.getDefaultInstance();
      } else {
        if (requestCase_ == 1) {
          return listRequestBuilder_.getMessage();
        }
        return ru.itmo.java.message.tracker.ListRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.tracker.ListRequest listRequest = 1;</code>
     */
    public Builder setListRequest(ru.itmo.java.message.tracker.ListRequest value) {
      if (listRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        request_ = value;
        onChanged();
      } else {
        listRequestBuilder_.setMessage(value);
      }
      requestCase_ = 1;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.ListRequest listRequest = 1;</code>
     */
    public Builder setListRequest(
        ru.itmo.java.message.tracker.ListRequest.Builder builderForValue) {
      if (listRequestBuilder_ == null) {
        request_ = builderForValue.build();
        onChanged();
      } else {
        listRequestBuilder_.setMessage(builderForValue.build());
      }
      requestCase_ = 1;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.ListRequest listRequest = 1;</code>
     */
    public Builder mergeListRequest(ru.itmo.java.message.tracker.ListRequest value) {
      if (listRequestBuilder_ == null) {
        if (requestCase_ == 1 &&
            request_ != ru.itmo.java.message.tracker.ListRequest.getDefaultInstance()) {
          request_ = ru.itmo.java.message.tracker.ListRequest.newBuilder((ru.itmo.java.message.tracker.ListRequest) request_)
              .mergeFrom(value).buildPartial();
        } else {
          request_ = value;
        }
        onChanged();
      } else {
        if (requestCase_ == 1) {
          listRequestBuilder_.mergeFrom(value);
        }
        listRequestBuilder_.setMessage(value);
      }
      requestCase_ = 1;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.ListRequest listRequest = 1;</code>
     */
    public Builder clearListRequest() {
      if (listRequestBuilder_ == null) {
        if (requestCase_ == 1) {
          requestCase_ = 0;
          request_ = null;
          onChanged();
        }
      } else {
        if (requestCase_ == 1) {
          requestCase_ = 0;
          request_ = null;
        }
        listRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.ListRequest listRequest = 1;</code>
     */
    public ru.itmo.java.message.tracker.ListRequest.Builder getListRequestBuilder() {
      return getListRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.ru.itmo.java.message.tracker.ListRequest listRequest = 1;</code>
     */
    @java.lang.Override
    public ru.itmo.java.message.tracker.ListRequestOrBuilder getListRequestOrBuilder() {
      if ((requestCase_ == 1) && (listRequestBuilder_ != null)) {
        return listRequestBuilder_.getMessageOrBuilder();
      } else {
        if (requestCase_ == 1) {
          return (ru.itmo.java.message.tracker.ListRequest) request_;
        }
        return ru.itmo.java.message.tracker.ListRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.tracker.ListRequest listRequest = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.tracker.ListRequest, ru.itmo.java.message.tracker.ListRequest.Builder, ru.itmo.java.message.tracker.ListRequestOrBuilder> 
        getListRequestFieldBuilder() {
      if (listRequestBuilder_ == null) {
        if (!(requestCase_ == 1)) {
          request_ = ru.itmo.java.message.tracker.ListRequest.getDefaultInstance();
        }
        listRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ru.itmo.java.message.tracker.ListRequest, ru.itmo.java.message.tracker.ListRequest.Builder, ru.itmo.java.message.tracker.ListRequestOrBuilder>(
                (ru.itmo.java.message.tracker.ListRequest) request_,
                getParentForChildren(),
                isClean());
        request_ = null;
      }
      requestCase_ = 1;
      onChanged();;
      return listRequestBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.tracker.UploadRequest, ru.itmo.java.message.tracker.UploadRequest.Builder, ru.itmo.java.message.tracker.UploadRequestOrBuilder> uploadRequestBuilder_;
    /**
     * <code>.ru.itmo.java.message.tracker.UploadRequest uploadRequest = 2;</code>
     * @return Whether the uploadRequest field is set.
     */
    @java.lang.Override
    public boolean hasUploadRequest() {
      return requestCase_ == 2;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UploadRequest uploadRequest = 2;</code>
     * @return The uploadRequest.
     */
    @java.lang.Override
    public ru.itmo.java.message.tracker.UploadRequest getUploadRequest() {
      if (uploadRequestBuilder_ == null) {
        if (requestCase_ == 2) {
          return (ru.itmo.java.message.tracker.UploadRequest) request_;
        }
        return ru.itmo.java.message.tracker.UploadRequest.getDefaultInstance();
      } else {
        if (requestCase_ == 2) {
          return uploadRequestBuilder_.getMessage();
        }
        return ru.itmo.java.message.tracker.UploadRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UploadRequest uploadRequest = 2;</code>
     */
    public Builder setUploadRequest(ru.itmo.java.message.tracker.UploadRequest value) {
      if (uploadRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        request_ = value;
        onChanged();
      } else {
        uploadRequestBuilder_.setMessage(value);
      }
      requestCase_ = 2;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UploadRequest uploadRequest = 2;</code>
     */
    public Builder setUploadRequest(
        ru.itmo.java.message.tracker.UploadRequest.Builder builderForValue) {
      if (uploadRequestBuilder_ == null) {
        request_ = builderForValue.build();
        onChanged();
      } else {
        uploadRequestBuilder_.setMessage(builderForValue.build());
      }
      requestCase_ = 2;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UploadRequest uploadRequest = 2;</code>
     */
    public Builder mergeUploadRequest(ru.itmo.java.message.tracker.UploadRequest value) {
      if (uploadRequestBuilder_ == null) {
        if (requestCase_ == 2 &&
            request_ != ru.itmo.java.message.tracker.UploadRequest.getDefaultInstance()) {
          request_ = ru.itmo.java.message.tracker.UploadRequest.newBuilder((ru.itmo.java.message.tracker.UploadRequest) request_)
              .mergeFrom(value).buildPartial();
        } else {
          request_ = value;
        }
        onChanged();
      } else {
        if (requestCase_ == 2) {
          uploadRequestBuilder_.mergeFrom(value);
        }
        uploadRequestBuilder_.setMessage(value);
      }
      requestCase_ = 2;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UploadRequest uploadRequest = 2;</code>
     */
    public Builder clearUploadRequest() {
      if (uploadRequestBuilder_ == null) {
        if (requestCase_ == 2) {
          requestCase_ = 0;
          request_ = null;
          onChanged();
        }
      } else {
        if (requestCase_ == 2) {
          requestCase_ = 0;
          request_ = null;
        }
        uploadRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UploadRequest uploadRequest = 2;</code>
     */
    public ru.itmo.java.message.tracker.UploadRequest.Builder getUploadRequestBuilder() {
      return getUploadRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UploadRequest uploadRequest = 2;</code>
     */
    @java.lang.Override
    public ru.itmo.java.message.tracker.UploadRequestOrBuilder getUploadRequestOrBuilder() {
      if ((requestCase_ == 2) && (uploadRequestBuilder_ != null)) {
        return uploadRequestBuilder_.getMessageOrBuilder();
      } else {
        if (requestCase_ == 2) {
          return (ru.itmo.java.message.tracker.UploadRequest) request_;
        }
        return ru.itmo.java.message.tracker.UploadRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UploadRequest uploadRequest = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.tracker.UploadRequest, ru.itmo.java.message.tracker.UploadRequest.Builder, ru.itmo.java.message.tracker.UploadRequestOrBuilder> 
        getUploadRequestFieldBuilder() {
      if (uploadRequestBuilder_ == null) {
        if (!(requestCase_ == 2)) {
          request_ = ru.itmo.java.message.tracker.UploadRequest.getDefaultInstance();
        }
        uploadRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ru.itmo.java.message.tracker.UploadRequest, ru.itmo.java.message.tracker.UploadRequest.Builder, ru.itmo.java.message.tracker.UploadRequestOrBuilder>(
                (ru.itmo.java.message.tracker.UploadRequest) request_,
                getParentForChildren(),
                isClean());
        request_ = null;
      }
      requestCase_ = 2;
      onChanged();;
      return uploadRequestBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.tracker.SourcesRequest, ru.itmo.java.message.tracker.SourcesRequest.Builder, ru.itmo.java.message.tracker.SourcesRequestOrBuilder> sourcesRequestBuilder_;
    /**
     * <code>.ru.itmo.java.message.tracker.SourcesRequest sourcesRequest = 3;</code>
     * @return Whether the sourcesRequest field is set.
     */
    @java.lang.Override
    public boolean hasSourcesRequest() {
      return requestCase_ == 3;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.SourcesRequest sourcesRequest = 3;</code>
     * @return The sourcesRequest.
     */
    @java.lang.Override
    public ru.itmo.java.message.tracker.SourcesRequest getSourcesRequest() {
      if (sourcesRequestBuilder_ == null) {
        if (requestCase_ == 3) {
          return (ru.itmo.java.message.tracker.SourcesRequest) request_;
        }
        return ru.itmo.java.message.tracker.SourcesRequest.getDefaultInstance();
      } else {
        if (requestCase_ == 3) {
          return sourcesRequestBuilder_.getMessage();
        }
        return ru.itmo.java.message.tracker.SourcesRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.tracker.SourcesRequest sourcesRequest = 3;</code>
     */
    public Builder setSourcesRequest(ru.itmo.java.message.tracker.SourcesRequest value) {
      if (sourcesRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        request_ = value;
        onChanged();
      } else {
        sourcesRequestBuilder_.setMessage(value);
      }
      requestCase_ = 3;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.SourcesRequest sourcesRequest = 3;</code>
     */
    public Builder setSourcesRequest(
        ru.itmo.java.message.tracker.SourcesRequest.Builder builderForValue) {
      if (sourcesRequestBuilder_ == null) {
        request_ = builderForValue.build();
        onChanged();
      } else {
        sourcesRequestBuilder_.setMessage(builderForValue.build());
      }
      requestCase_ = 3;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.SourcesRequest sourcesRequest = 3;</code>
     */
    public Builder mergeSourcesRequest(ru.itmo.java.message.tracker.SourcesRequest value) {
      if (sourcesRequestBuilder_ == null) {
        if (requestCase_ == 3 &&
            request_ != ru.itmo.java.message.tracker.SourcesRequest.getDefaultInstance()) {
          request_ = ru.itmo.java.message.tracker.SourcesRequest.newBuilder((ru.itmo.java.message.tracker.SourcesRequest) request_)
              .mergeFrom(value).buildPartial();
        } else {
          request_ = value;
        }
        onChanged();
      } else {
        if (requestCase_ == 3) {
          sourcesRequestBuilder_.mergeFrom(value);
        }
        sourcesRequestBuilder_.setMessage(value);
      }
      requestCase_ = 3;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.SourcesRequest sourcesRequest = 3;</code>
     */
    public Builder clearSourcesRequest() {
      if (sourcesRequestBuilder_ == null) {
        if (requestCase_ == 3) {
          requestCase_ = 0;
          request_ = null;
          onChanged();
        }
      } else {
        if (requestCase_ == 3) {
          requestCase_ = 0;
          request_ = null;
        }
        sourcesRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.SourcesRequest sourcesRequest = 3;</code>
     */
    public ru.itmo.java.message.tracker.SourcesRequest.Builder getSourcesRequestBuilder() {
      return getSourcesRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.ru.itmo.java.message.tracker.SourcesRequest sourcesRequest = 3;</code>
     */
    @java.lang.Override
    public ru.itmo.java.message.tracker.SourcesRequestOrBuilder getSourcesRequestOrBuilder() {
      if ((requestCase_ == 3) && (sourcesRequestBuilder_ != null)) {
        return sourcesRequestBuilder_.getMessageOrBuilder();
      } else {
        if (requestCase_ == 3) {
          return (ru.itmo.java.message.tracker.SourcesRequest) request_;
        }
        return ru.itmo.java.message.tracker.SourcesRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.tracker.SourcesRequest sourcesRequest = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.tracker.SourcesRequest, ru.itmo.java.message.tracker.SourcesRequest.Builder, ru.itmo.java.message.tracker.SourcesRequestOrBuilder> 
        getSourcesRequestFieldBuilder() {
      if (sourcesRequestBuilder_ == null) {
        if (!(requestCase_ == 3)) {
          request_ = ru.itmo.java.message.tracker.SourcesRequest.getDefaultInstance();
        }
        sourcesRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ru.itmo.java.message.tracker.SourcesRequest, ru.itmo.java.message.tracker.SourcesRequest.Builder, ru.itmo.java.message.tracker.SourcesRequestOrBuilder>(
                (ru.itmo.java.message.tracker.SourcesRequest) request_,
                getParentForChildren(),
                isClean());
        request_ = null;
      }
      requestCase_ = 3;
      onChanged();;
      return sourcesRequestBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.tracker.UpdateRequest, ru.itmo.java.message.tracker.UpdateRequest.Builder, ru.itmo.java.message.tracker.UpdateRequestOrBuilder> updateRequestBuilder_;
    /**
     * <code>.ru.itmo.java.message.tracker.UpdateRequest updateRequest = 4;</code>
     * @return Whether the updateRequest field is set.
     */
    @java.lang.Override
    public boolean hasUpdateRequest() {
      return requestCase_ == 4;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UpdateRequest updateRequest = 4;</code>
     * @return The updateRequest.
     */
    @java.lang.Override
    public ru.itmo.java.message.tracker.UpdateRequest getUpdateRequest() {
      if (updateRequestBuilder_ == null) {
        if (requestCase_ == 4) {
          return (ru.itmo.java.message.tracker.UpdateRequest) request_;
        }
        return ru.itmo.java.message.tracker.UpdateRequest.getDefaultInstance();
      } else {
        if (requestCase_ == 4) {
          return updateRequestBuilder_.getMessage();
        }
        return ru.itmo.java.message.tracker.UpdateRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UpdateRequest updateRequest = 4;</code>
     */
    public Builder setUpdateRequest(ru.itmo.java.message.tracker.UpdateRequest value) {
      if (updateRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        request_ = value;
        onChanged();
      } else {
        updateRequestBuilder_.setMessage(value);
      }
      requestCase_ = 4;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UpdateRequest updateRequest = 4;</code>
     */
    public Builder setUpdateRequest(
        ru.itmo.java.message.tracker.UpdateRequest.Builder builderForValue) {
      if (updateRequestBuilder_ == null) {
        request_ = builderForValue.build();
        onChanged();
      } else {
        updateRequestBuilder_.setMessage(builderForValue.build());
      }
      requestCase_ = 4;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UpdateRequest updateRequest = 4;</code>
     */
    public Builder mergeUpdateRequest(ru.itmo.java.message.tracker.UpdateRequest value) {
      if (updateRequestBuilder_ == null) {
        if (requestCase_ == 4 &&
            request_ != ru.itmo.java.message.tracker.UpdateRequest.getDefaultInstance()) {
          request_ = ru.itmo.java.message.tracker.UpdateRequest.newBuilder((ru.itmo.java.message.tracker.UpdateRequest) request_)
              .mergeFrom(value).buildPartial();
        } else {
          request_ = value;
        }
        onChanged();
      } else {
        if (requestCase_ == 4) {
          updateRequestBuilder_.mergeFrom(value);
        }
        updateRequestBuilder_.setMessage(value);
      }
      requestCase_ = 4;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UpdateRequest updateRequest = 4;</code>
     */
    public Builder clearUpdateRequest() {
      if (updateRequestBuilder_ == null) {
        if (requestCase_ == 4) {
          requestCase_ = 0;
          request_ = null;
          onChanged();
        }
      } else {
        if (requestCase_ == 4) {
          requestCase_ = 0;
          request_ = null;
        }
        updateRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UpdateRequest updateRequest = 4;</code>
     */
    public ru.itmo.java.message.tracker.UpdateRequest.Builder getUpdateRequestBuilder() {
      return getUpdateRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UpdateRequest updateRequest = 4;</code>
     */
    @java.lang.Override
    public ru.itmo.java.message.tracker.UpdateRequestOrBuilder getUpdateRequestOrBuilder() {
      if ((requestCase_ == 4) && (updateRequestBuilder_ != null)) {
        return updateRequestBuilder_.getMessageOrBuilder();
      } else {
        if (requestCase_ == 4) {
          return (ru.itmo.java.message.tracker.UpdateRequest) request_;
        }
        return ru.itmo.java.message.tracker.UpdateRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UpdateRequest updateRequest = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.tracker.UpdateRequest, ru.itmo.java.message.tracker.UpdateRequest.Builder, ru.itmo.java.message.tracker.UpdateRequestOrBuilder> 
        getUpdateRequestFieldBuilder() {
      if (updateRequestBuilder_ == null) {
        if (!(requestCase_ == 4)) {
          request_ = ru.itmo.java.message.tracker.UpdateRequest.getDefaultInstance();
        }
        updateRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ru.itmo.java.message.tracker.UpdateRequest, ru.itmo.java.message.tracker.UpdateRequest.Builder, ru.itmo.java.message.tracker.UpdateRequestOrBuilder>(
                (ru.itmo.java.message.tracker.UpdateRequest) request_,
                getParentForChildren(),
                isClean());
        request_ = null;
      }
      requestCase_ = 4;
      onChanged();;
      return updateRequestBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.tracker.StatRequest, ru.itmo.java.message.tracker.StatRequest.Builder, ru.itmo.java.message.tracker.StatRequestOrBuilder> statRequestBuilder_;
    /**
     * <code>.ru.itmo.java.message.tracker.StatRequest statRequest = 5;</code>
     * @return Whether the statRequest field is set.
     */
    @java.lang.Override
    public boolean hasStatRequest() {
      return requestCase_ == 5;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.StatRequest statRequest = 5;</code>
     * @return The statRequest.
     */
    @java.lang.Override
    public ru.itmo.java.message.tracker.StatRequest getStatRequest() {
      if (statRequestBuilder_ == null) {
        if (requestCase_ == 5) {
          return (ru.itmo.java.message.tracker.StatRequest) request_;
        }
        return ru.itmo.java.message.tracker.StatRequest.getDefaultInstance();
      } else {
        if (requestCase_ == 5) {
          return statRequestBuilder_.getMessage();
        }
        return ru.itmo.java.message.tracker.StatRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.tracker.StatRequest statRequest = 5;</code>
     */
    public Builder setStatRequest(ru.itmo.java.message.tracker.StatRequest value) {
      if (statRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        request_ = value;
        onChanged();
      } else {
        statRequestBuilder_.setMessage(value);
      }
      requestCase_ = 5;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.StatRequest statRequest = 5;</code>
     */
    public Builder setStatRequest(
        ru.itmo.java.message.tracker.StatRequest.Builder builderForValue) {
      if (statRequestBuilder_ == null) {
        request_ = builderForValue.build();
        onChanged();
      } else {
        statRequestBuilder_.setMessage(builderForValue.build());
      }
      requestCase_ = 5;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.StatRequest statRequest = 5;</code>
     */
    public Builder mergeStatRequest(ru.itmo.java.message.tracker.StatRequest value) {
      if (statRequestBuilder_ == null) {
        if (requestCase_ == 5 &&
            request_ != ru.itmo.java.message.tracker.StatRequest.getDefaultInstance()) {
          request_ = ru.itmo.java.message.tracker.StatRequest.newBuilder((ru.itmo.java.message.tracker.StatRequest) request_)
              .mergeFrom(value).buildPartial();
        } else {
          request_ = value;
        }
        onChanged();
      } else {
        if (requestCase_ == 5) {
          statRequestBuilder_.mergeFrom(value);
        }
        statRequestBuilder_.setMessage(value);
      }
      requestCase_ = 5;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.StatRequest statRequest = 5;</code>
     */
    public Builder clearStatRequest() {
      if (statRequestBuilder_ == null) {
        if (requestCase_ == 5) {
          requestCase_ = 0;
          request_ = null;
          onChanged();
        }
      } else {
        if (requestCase_ == 5) {
          requestCase_ = 0;
          request_ = null;
        }
        statRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.StatRequest statRequest = 5;</code>
     */
    public ru.itmo.java.message.tracker.StatRequest.Builder getStatRequestBuilder() {
      return getStatRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.ru.itmo.java.message.tracker.StatRequest statRequest = 5;</code>
     */
    @java.lang.Override
    public ru.itmo.java.message.tracker.StatRequestOrBuilder getStatRequestOrBuilder() {
      if ((requestCase_ == 5) && (statRequestBuilder_ != null)) {
        return statRequestBuilder_.getMessageOrBuilder();
      } else {
        if (requestCase_ == 5) {
          return (ru.itmo.java.message.tracker.StatRequest) request_;
        }
        return ru.itmo.java.message.tracker.StatRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.tracker.StatRequest statRequest = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.tracker.StatRequest, ru.itmo.java.message.tracker.StatRequest.Builder, ru.itmo.java.message.tracker.StatRequestOrBuilder> 
        getStatRequestFieldBuilder() {
      if (statRequestBuilder_ == null) {
        if (!(requestCase_ == 5)) {
          request_ = ru.itmo.java.message.tracker.StatRequest.getDefaultInstance();
        }
        statRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ru.itmo.java.message.tracker.StatRequest, ru.itmo.java.message.tracker.StatRequest.Builder, ru.itmo.java.message.tracker.StatRequestOrBuilder>(
                (ru.itmo.java.message.tracker.StatRequest) request_,
                getParentForChildren(),
                isClean());
        request_ = null;
      }
      requestCase_ = 5;
      onChanged();;
      return statRequestBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.tracker.GetRequest, ru.itmo.java.message.tracker.GetRequest.Builder, ru.itmo.java.message.tracker.GetRequestOrBuilder> getRequestBuilder_;
    /**
     * <code>.ru.itmo.java.message.tracker.GetRequest getRequest = 6;</code>
     * @return Whether the getRequest field is set.
     */
    @java.lang.Override
    public boolean hasGetRequest() {
      return requestCase_ == 6;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.GetRequest getRequest = 6;</code>
     * @return The getRequest.
     */
    @java.lang.Override
    public ru.itmo.java.message.tracker.GetRequest getGetRequest() {
      if (getRequestBuilder_ == null) {
        if (requestCase_ == 6) {
          return (ru.itmo.java.message.tracker.GetRequest) request_;
        }
        return ru.itmo.java.message.tracker.GetRequest.getDefaultInstance();
      } else {
        if (requestCase_ == 6) {
          return getRequestBuilder_.getMessage();
        }
        return ru.itmo.java.message.tracker.GetRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.tracker.GetRequest getRequest = 6;</code>
     */
    public Builder setGetRequest(ru.itmo.java.message.tracker.GetRequest value) {
      if (getRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        request_ = value;
        onChanged();
      } else {
        getRequestBuilder_.setMessage(value);
      }
      requestCase_ = 6;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.GetRequest getRequest = 6;</code>
     */
    public Builder setGetRequest(
        ru.itmo.java.message.tracker.GetRequest.Builder builderForValue) {
      if (getRequestBuilder_ == null) {
        request_ = builderForValue.build();
        onChanged();
      } else {
        getRequestBuilder_.setMessage(builderForValue.build());
      }
      requestCase_ = 6;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.GetRequest getRequest = 6;</code>
     */
    public Builder mergeGetRequest(ru.itmo.java.message.tracker.GetRequest value) {
      if (getRequestBuilder_ == null) {
        if (requestCase_ == 6 &&
            request_ != ru.itmo.java.message.tracker.GetRequest.getDefaultInstance()) {
          request_ = ru.itmo.java.message.tracker.GetRequest.newBuilder((ru.itmo.java.message.tracker.GetRequest) request_)
              .mergeFrom(value).buildPartial();
        } else {
          request_ = value;
        }
        onChanged();
      } else {
        if (requestCase_ == 6) {
          getRequestBuilder_.mergeFrom(value);
        }
        getRequestBuilder_.setMessage(value);
      }
      requestCase_ = 6;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.GetRequest getRequest = 6;</code>
     */
    public Builder clearGetRequest() {
      if (getRequestBuilder_ == null) {
        if (requestCase_ == 6) {
          requestCase_ = 0;
          request_ = null;
          onChanged();
        }
      } else {
        if (requestCase_ == 6) {
          requestCase_ = 0;
          request_ = null;
        }
        getRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.GetRequest getRequest = 6;</code>
     */
    public ru.itmo.java.message.tracker.GetRequest.Builder getGetRequestBuilder() {
      return getGetRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.ru.itmo.java.message.tracker.GetRequest getRequest = 6;</code>
     */
    @java.lang.Override
    public ru.itmo.java.message.tracker.GetRequestOrBuilder getGetRequestOrBuilder() {
      if ((requestCase_ == 6) && (getRequestBuilder_ != null)) {
        return getRequestBuilder_.getMessageOrBuilder();
      } else {
        if (requestCase_ == 6) {
          return (ru.itmo.java.message.tracker.GetRequest) request_;
        }
        return ru.itmo.java.message.tracker.GetRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.tracker.GetRequest getRequest = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.tracker.GetRequest, ru.itmo.java.message.tracker.GetRequest.Builder, ru.itmo.java.message.tracker.GetRequestOrBuilder> 
        getGetRequestFieldBuilder() {
      if (getRequestBuilder_ == null) {
        if (!(requestCase_ == 6)) {
          request_ = ru.itmo.java.message.tracker.GetRequest.getDefaultInstance();
        }
        getRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ru.itmo.java.message.tracker.GetRequest, ru.itmo.java.message.tracker.GetRequest.Builder, ru.itmo.java.message.tracker.GetRequestOrBuilder>(
                (ru.itmo.java.message.tracker.GetRequest) request_,
                getParentForChildren(),
                isClean());
        request_ = null;
      }
      requestCase_ = 6;
      onChanged();;
      return getRequestBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ru.itmo.java.message.tracker.BaseRequest)
  }

  // @@protoc_insertion_point(class_scope:ru.itmo.java.message.tracker.BaseRequest)
  private static final ru.itmo.java.message.tracker.BaseRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ru.itmo.java.message.tracker.BaseRequest();
  }

  public static ru.itmo.java.message.tracker.BaseRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BaseRequest>
      PARSER = new com.google.protobuf.AbstractParser<BaseRequest>() {
    @java.lang.Override
    public BaseRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BaseRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BaseRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BaseRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ru.itmo.java.message.tracker.BaseRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

