// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TrackerMessages.proto

package ru.itmo.java.message.tracker;

public interface SourcesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.itmo.java.message.tracker.SourcesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 size = 1;</code>
   * @return The size.
   */
  long getSize();

  /**
   * <code>repeated .ru.itmo.java.message.tracker.ClientInfo clients = 2;</code>
   */
  java.util.List<ru.itmo.java.message.tracker.ClientInfo> 
      getClientsList();
  /**
   * <code>repeated .ru.itmo.java.message.tracker.ClientInfo clients = 2;</code>
   */
  ru.itmo.java.message.tracker.ClientInfo getClients(int index);
  /**
   * <code>repeated .ru.itmo.java.message.tracker.ClientInfo clients = 2;</code>
   */
  int getClientsCount();
  /**
   * <code>repeated .ru.itmo.java.message.tracker.ClientInfo clients = 2;</code>
   */
  java.util.List<? extends ru.itmo.java.message.tracker.ClientInfoOrBuilder> 
      getClientsOrBuilderList();
  /**
   * <code>repeated .ru.itmo.java.message.tracker.ClientInfo clients = 2;</code>
   */
  ru.itmo.java.message.tracker.ClientInfoOrBuilder getClientsOrBuilder(
      int index);

  /**
   * <code>bool correctRequestId = 3;</code>
   * @return The correctRequestId.
   */
  boolean getCorrectRequestId();
}
