// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TrackerMessages.proto

package ru.itmo.java.message.tracker;

/**
 * Protobuf type {@code ru.itmo.java.message.tracker.StatResponse}
 */
public final class StatResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ru.itmo.java.message.tracker.StatResponse)
    StatResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StatResponse.newBuilder() to construct.
  private StatResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StatResponse() {
    completeParts_ = emptyLongList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new StatResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StatResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            numParts_ = input.readInt64();
            break;
          }
          case 16: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              completeParts_ = newLongList();
              mutable_bitField0_ |= 0x00000001;
            }
            completeParts_.addLong(input.readInt64());
            break;
          }
          case 18: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
              completeParts_ = newLongList();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              completeParts_.addLong(input.readInt64());
            }
            input.popLimit(limit);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        completeParts_.makeImmutable(); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ru.itmo.java.message.tracker.TrackerMessages.internal_static_ru_itmo_java_message_tracker_StatResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ru.itmo.java.message.tracker.TrackerMessages.internal_static_ru_itmo_java_message_tracker_StatResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ru.itmo.java.message.tracker.StatResponse.class, ru.itmo.java.message.tracker.StatResponse.Builder.class);
  }

  public static final int NUMPARTS_FIELD_NUMBER = 1;
  private long numParts_;
  /**
   * <code>int64 numParts = 1;</code>
   * @return The numParts.
   */
  @java.lang.Override
  public long getNumParts() {
    return numParts_;
  }

  public static final int COMPLETEPARTS_FIELD_NUMBER = 2;
  private com.google.protobuf.Internal.LongList completeParts_;
  /**
   * <code>repeated int64 completeParts = 2;</code>
   * @return A list containing the completeParts.
   */
  @java.lang.Override
  public java.util.List<java.lang.Long>
      getCompletePartsList() {
    return completeParts_;
  }
  /**
   * <code>repeated int64 completeParts = 2;</code>
   * @return The count of completeParts.
   */
  public int getCompletePartsCount() {
    return completeParts_.size();
  }
  /**
   * <code>repeated int64 completeParts = 2;</code>
   * @param index The index of the element to return.
   * @return The completeParts at the given index.
   */
  public long getCompleteParts(int index) {
    return completeParts_.getLong(index);
  }
  private int completePartsMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (numParts_ != 0L) {
      output.writeInt64(1, numParts_);
    }
    if (getCompletePartsList().size() > 0) {
      output.writeUInt32NoTag(18);
      output.writeUInt32NoTag(completePartsMemoizedSerializedSize);
    }
    for (int i = 0; i < completeParts_.size(); i++) {
      output.writeInt64NoTag(completeParts_.getLong(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (numParts_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, numParts_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < completeParts_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(completeParts_.getLong(i));
      }
      size += dataSize;
      if (!getCompletePartsList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      completePartsMemoizedSerializedSize = dataSize;
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ru.itmo.java.message.tracker.StatResponse)) {
      return super.equals(obj);
    }
    ru.itmo.java.message.tracker.StatResponse other = (ru.itmo.java.message.tracker.StatResponse) obj;

    if (getNumParts()
        != other.getNumParts()) return false;
    if (!getCompletePartsList()
        .equals(other.getCompletePartsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NUMPARTS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getNumParts());
    if (getCompletePartsCount() > 0) {
      hash = (37 * hash) + COMPLETEPARTS_FIELD_NUMBER;
      hash = (53 * hash) + getCompletePartsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ru.itmo.java.message.tracker.StatResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.itmo.java.message.tracker.StatResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.itmo.java.message.tracker.StatResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.itmo.java.message.tracker.StatResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.itmo.java.message.tracker.StatResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.itmo.java.message.tracker.StatResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.itmo.java.message.tracker.StatResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.itmo.java.message.tracker.StatResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.itmo.java.message.tracker.StatResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ru.itmo.java.message.tracker.StatResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.itmo.java.message.tracker.StatResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.itmo.java.message.tracker.StatResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ru.itmo.java.message.tracker.StatResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ru.itmo.java.message.tracker.StatResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ru.itmo.java.message.tracker.StatResponse)
      ru.itmo.java.message.tracker.StatResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.itmo.java.message.tracker.TrackerMessages.internal_static_ru_itmo_java_message_tracker_StatResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.itmo.java.message.tracker.TrackerMessages.internal_static_ru_itmo_java_message_tracker_StatResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.itmo.java.message.tracker.StatResponse.class, ru.itmo.java.message.tracker.StatResponse.Builder.class);
    }

    // Construct using ru.itmo.java.message.tracker.StatResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      numParts_ = 0L;

      completeParts_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ru.itmo.java.message.tracker.TrackerMessages.internal_static_ru_itmo_java_message_tracker_StatResponse_descriptor;
    }

    @java.lang.Override
    public ru.itmo.java.message.tracker.StatResponse getDefaultInstanceForType() {
      return ru.itmo.java.message.tracker.StatResponse.getDefaultInstance();
    }

    @java.lang.Override
    public ru.itmo.java.message.tracker.StatResponse build() {
      ru.itmo.java.message.tracker.StatResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ru.itmo.java.message.tracker.StatResponse buildPartial() {
      ru.itmo.java.message.tracker.StatResponse result = new ru.itmo.java.message.tracker.StatResponse(this);
      int from_bitField0_ = bitField0_;
      result.numParts_ = numParts_;
      if (((bitField0_ & 0x00000001) != 0)) {
        completeParts_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.completeParts_ = completeParts_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ru.itmo.java.message.tracker.StatResponse) {
        return mergeFrom((ru.itmo.java.message.tracker.StatResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ru.itmo.java.message.tracker.StatResponse other) {
      if (other == ru.itmo.java.message.tracker.StatResponse.getDefaultInstance()) return this;
      if (other.getNumParts() != 0L) {
        setNumParts(other.getNumParts());
      }
      if (!other.completeParts_.isEmpty()) {
        if (completeParts_.isEmpty()) {
          completeParts_ = other.completeParts_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureCompletePartsIsMutable();
          completeParts_.addAll(other.completeParts_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ru.itmo.java.message.tracker.StatResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ru.itmo.java.message.tracker.StatResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long numParts_ ;
    /**
     * <code>int64 numParts = 1;</code>
     * @return The numParts.
     */
    @java.lang.Override
    public long getNumParts() {
      return numParts_;
    }
    /**
     * <code>int64 numParts = 1;</code>
     * @param value The numParts to set.
     * @return This builder for chaining.
     */
    public Builder setNumParts(long value) {
      
      numParts_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 numParts = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumParts() {
      
      numParts_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.LongList completeParts_ = emptyLongList();
    private void ensureCompletePartsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        completeParts_ = mutableCopy(completeParts_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated int64 completeParts = 2;</code>
     * @return A list containing the completeParts.
     */
    public java.util.List<java.lang.Long>
        getCompletePartsList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(completeParts_) : completeParts_;
    }
    /**
     * <code>repeated int64 completeParts = 2;</code>
     * @return The count of completeParts.
     */
    public int getCompletePartsCount() {
      return completeParts_.size();
    }
    /**
     * <code>repeated int64 completeParts = 2;</code>
     * @param index The index of the element to return.
     * @return The completeParts at the given index.
     */
    public long getCompleteParts(int index) {
      return completeParts_.getLong(index);
    }
    /**
     * <code>repeated int64 completeParts = 2;</code>
     * @param index The index to set the value at.
     * @param value The completeParts to set.
     * @return This builder for chaining.
     */
    public Builder setCompleteParts(
        int index, long value) {
      ensureCompletePartsIsMutable();
      completeParts_.setLong(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 completeParts = 2;</code>
     * @param value The completeParts to add.
     * @return This builder for chaining.
     */
    public Builder addCompleteParts(long value) {
      ensureCompletePartsIsMutable();
      completeParts_.addLong(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 completeParts = 2;</code>
     * @param values The completeParts to add.
     * @return This builder for chaining.
     */
    public Builder addAllCompleteParts(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureCompletePartsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, completeParts_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 completeParts = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCompleteParts() {
      completeParts_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ru.itmo.java.message.tracker.StatResponse)
  }

  // @@protoc_insertion_point(class_scope:ru.itmo.java.message.tracker.StatResponse)
  private static final ru.itmo.java.message.tracker.StatResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ru.itmo.java.message.tracker.StatResponse();
  }

  public static ru.itmo.java.message.tracker.StatResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StatResponse>
      PARSER = new com.google.protobuf.AbstractParser<StatResponse>() {
    @java.lang.Override
    public StatResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StatResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StatResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StatResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ru.itmo.java.message.tracker.StatResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

