// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TrackerMessages.proto

package ru.itmo.java.message.tracker;

public interface StatResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.itmo.java.message.tracker.StatResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 numParts = 1;</code>
   * @return The numParts.
   */
  long getNumParts();

  /**
   * <code>repeated int64 completeParts = 2;</code>
   * @return A list containing the completeParts.
   */
  java.util.List<java.lang.Long> getCompletePartsList();
  /**
   * <code>repeated int64 completeParts = 2;</code>
   * @return The count of completeParts.
   */
  int getCompletePartsCount();
  /**
   * <code>repeated int64 completeParts = 2;</code>
   * @param index The index of the element to return.
   * @return The completeParts at the given index.
   */
  long getCompleteParts(int index);
}
