// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TrackerMessages.proto

package ru.itmo.java.message.tracker;

public interface UpdateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.itmo.java.message.tracker.UpdateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 clientPort = 1;</code>
   * @return The clientPort.
   */
  int getClientPort();

  /**
   * <code>int64 count = 2;</code>
   * @return The count.
   */
  long getCount();

  /**
   * <code>repeated int64 id = 3;</code>
   * @return A list containing the id.
   */
  java.util.List<java.lang.Long> getIdList();
  /**
   * <code>repeated int64 id = 3;</code>
   * @return The count of id.
   */
  int getIdCount();
  /**
   * <code>repeated int64 id = 3;</code>
   * @param index The index of the element to return.
   * @return The id at the given index.
   */
  long getId(int index);
}
